//システム設定変更のため %SYSネームスペースに移動
set $namespace="%SYS"
// 事前定義ユーザのパスワードを無期限に設定する（デフォルトパスワードはSYS）
Do ##class(Security.Users).UnExpireUserPasswords("*")
// 日本語ロケールに変更（コンテナがUbuntu英語版のためデフォルトは英語ロケール）を利用
Do ##class(Config.NLS.Locales).Install("jpuw")

//USERに移動してソースコードインポート
set $namespace="USER"
do $system.OBJ.ImportDir("/opt/app/src",,"ck",,1)
//Webページが利用するREST用パス設定
do ##class(App.Setup).SetRESTPath()
//サンプルデータ作成
//do ##class(App.Setup).CreateSampleData()

halt